In [1]:
import numpy as np

In [2]:
# The .arange() function, short for “array range”, is a function that creates an array with evenly spaced values.

# For example:

arr = np.arange(5)

print(arr)  # Output: [0 1 2 3 4]

[0 1 2 3 4]


In [3]:
# You can go further with its three parameters:

    # start is the first value in the array.
    # stop is end of the range.
    # step is step size of the intervals.

# For example:

arr = np.arange(start=1, stop=10, step=3)

print(arr)  # Output: [1 4 7]

[1 4 7]


In [4]:
halleys_commet = np.arange(start=1986, stop=3000, step=75)
print(halleys_commet)


[1986 2061 2136 2211 2286 2361 2436 2511 2586 2661 2736 2811 2886 2961]
