# Indexing

## A. Array accessing

Accessing NumPy arrays is identical to accessing Python lists. For multi-dimensional arrays, it is equivalent to accessing Python lists of lists.

The code below shows example accesses of NumPy arrays.

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[4])

arr = np.array([[6, 3], [0, 2]])
# Subarray
print(arr[0][1])

1
5
3


## B. Slicing

NumPy arrays also support slicing. Similar to Python, we use the colon operator (i.e. arr[:]) for slicing. We can also use negative indexing to slice in the backwards direction.

The code below shows example slices of a 1-D NumPy array.

In [4]:
arr = np.array([1, 2, 3, 4, 5])
print(repr(arr[:]))
print(repr(arr[1:]))
print(repr(arr[2:4]))
print(repr(arr[:-1]))
print(repr(arr[-2:]))


array([1, 2, 3, 4, 5])
array([2, 3, 4, 5])
array([3, 4])
array([1, 2, 3, 4])
array([4, 5])


For multi-dimensional arrays, we can use a comma to separate slices across each dimension.

The code below shows example slices of a 2-D NumPy array.

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(repr(arr[:]))
print(repr(arr[1:]))
print(repr(arr[:, -1]))
print(repr(arr[:, 1:]))
print(repr(arr[0:1, 1:]))
print(repr(arr[0, 1:]))


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
array([[4, 5, 6],
       [7, 8, 9]])
array([3, 6, 9])
array([[2, 3],
       [5, 6],
       [8, 9]])
array([[2, 3]])
array([2, 3])


## C. Argmin and argmax

In addition to accessing and slicing arrays, it is useful to figure out the actual indexes of the minimum and maximum elements. To do this, we use the np.argmin and np.argmax functions.

The code below shows example usages of np.argmin and np.argmax. Note that the index of element -6 is index 5 in the flattened version of arr.

In [7]:
arr = np.array([[-2, -1, -3], [4, 5, -6], [-3, 9, 1]])
print(f"Min[0] at index: {np.argmin(arr[0])}")
print(f"Max[2] at index: {np.argmax(arr[2])}")
print(f"Min[arr] at index: {np.argmin(arr)}")


Min[0] at index: 2
Max[2] at index: 1
Min[arr] at index: 5


The np.argmin and np.argmax functions take the same arguments. The required argument is the input array and the axis keyword argument specifies which dimension to apply the operation on.

The code below shows how the axis keyword argument is used for these functions.

In [8]:
arr = np.array([[-2, -1, -3], [4, 5, -6], [-3, 9, 1]])
print(repr(np.argmin(arr, axis=0)))
print(repr(np.argmin(arr, axis=1)))
print(repr(np.argmax(arr, axis=-1)))


array([2, 0, 1])
array([2, 2, 0])
array([1, 1, 1])


In our example, using axis=0 meant the function found the index of the minimum row element for each column. When we used axis=1, the function found the index of the minimum column element for each row.

Setting axis to -1 just means we apply the function across the last dimension. In this case, axis=-1 is equivalent to axis=1.

# Time to Code!

Each coding exercise in this chapter will be to complete a small function that takes in a 2-D NumPy matrix (data) as input. The first function to complete is direct_index.

Set elem equal to the third element of the second row in data (remember that the first row is index 0). Then return elem.

In [9]:
def direct_index(data):
    elem = data[1][2]
    return elem


The next function, slice_data, will return two slices from the input data.

The first slice will contain all the rows, but will skip the first element in each row. The second slice will contain all the elements of the first three rows except the last two elements.

Return a tuple containing slice1 and slice2, in that order.

In [10]:
def slice_data(data: np.array) -> tuple:
    slice1 = data[:, 1:]
    slice2 = data[:3, :-2]
    return (slice1, slice2)

The next function, argmin_data, will find minimum indexes in the input data.

We can use np.argmin to find minimum points in the data array. First, we'll find the index of the overall minimum element.

We can also return the indexes of each row's minimum element. This is equivalent to finding the minimum column for each row, which means our operation is done along axis 1.

Return a tuple containing argmin_all and argmin1, in that order.

In [12]:
def argmin_data(data: np.array) -> tuple:
    argmin_all = np.argmin(data)
    argmin1 = np.argmin(data, axis = 1)
    return (argmin_all, argmin1)

The final function, argmax_data, will find the index of each row's maximum element in data. Since there are only 2 dimensions in data, we can apply the operation along either axis 1 or -1.

In [14]:
def argmax_data(data: np.array) -> int:
    argmax_neg1 = np.argmax()(data, axis = -1)
    return argmax_neg1