# A. Arithmetic

One of the main purposes of NumPy is to perform multi-dimensional arithmetic. Using NumPy arrays, we can apply arithmetic to each element with a single operation.

The code below shows multi-dimensional arithmetic with NumPy.

In [3]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
# Add 1 to element values
print(repr(arr + 1))
# Subtract element values by 1.2
print(repr(arr - 1.2))
# Double element values
print(repr(arr * 2))
# Halve element values
print(repr(arr / 2))
# Integer division (half)
print(repr(arr // 2))
# Square element values
print(repr(arr**2))
# Square root element values
print(repr(arr**0.5))


array([[2, 3],
       [4, 5]])
array([[-0.2,  0.8],
       [ 1.8,  2.8]])
array([[2, 4],
       [6, 8]])
array([[0.5, 1. ],
       [1.5, 2. ]])
array([[0, 1],
       [1, 2]])
array([[ 1,  4],
       [ 9, 16]])
array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])


Using NumPy arithmetic, we can easily modify large amounts of numeric data with only a few operations. For example, we could convert a dataset of Fahrenheit temperatures to their equivalent Celsius form.

The code below converts Fahrenheit to Celsius in NumPy.

In [4]:
def f2c(temps):
    return (5 / 9) * (temps - 32)


fahrenheits = np.array([32, -4, 14, -40])
celsius = f2c(fahrenheits)
print("Celsius: {}".format(repr(celsius)))


Celsius: array([  0., -20., -10., -40.])


Performing arithmetic on NumPy arrays does not change the original array, and instead produces a new array that is the result of the arithmetic operation.

# B. Non-linear functions

Apart from basic arithmetic operations, NumPy also allows you to use non-linear functions such as exponentials and logarithms.

The function np.exp performs a base e exponential on an array, while the function np.exp2 performs a base 2 exponential. Likewise, np.log, np.log2, and np.log10 all perform logarithms on an input array, using base e, base 2, and base 10, respectively.

The code below shows various exponentials and logarithms with NumPy. Note that np.e and np.pi represent the mathematical constants e and π, respectively.

In [5]:
arr = np.array([[1, 2], [3, 4]])
# Raised to power of e
print(repr(np.exp(arr)))
# Raised to power of 2
print(repr(np.exp2(arr)))

arr2 = np.array([[1, 10], [np.e, np.pi]])
# Natural logarithm
print(repr(np.log(arr2)))
# Base 10 logarithm
print(repr(np.log10(arr2)))


array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])
array([[ 2.,  4.],
       [ 8., 16.]])
array([[0.        , 2.30258509],
       [1.        , 1.14472989]])
array([[0.        , 1.        ],
       [0.43429448, 0.49714987]])


To do a regular power operation with any base, we use np.power. The first argument to the function is the base, while the second is the power. If the base or power is an array rather than a single number, the operation is applied to every element in the array.

The code below shows examples of using np.power.

In [17]:
arr = np.array([[1, 2], [3, 4]])
# Raise 3 to power of each number in arr
print(repr(np.power(3, arr)))
arr2 = np.array([[10.2, 4], [3, 5]])
# Raise arr2 to power of each number in arr
print(repr(np.power(arr2, arr)))


array([[ 3,  9],
       [27, 81]])
array([[ 10.2,  16. ],
       [ 27. , 625. ]])


# C. Matrix multiplication

Since NumPy arrays are basically vectors and matrices, it makes sense that there are functions for dot products and matrix multiplication. Specifically, the main function to use is np.matmul, which takes two vector/matrix arrays as input and produces a dot product or matrix multiplication.

The code below shows various examples of matrix multiplication. When both inputs are 1-D, the output is the dot product.

Note that the dimensions of the two input matrices must be valid for a matrix multiplication. Specifically, the second dimension of the first matrix must equal the first dimension of the second matrix, otherwise np.matmul will result in a ValueError.

In [20]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([-3, 0, 10])
print(np.matmul(arr1, arr2))

arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[-1, 0, 1], [3, 2, -4]])
print(repr(np.matmul(arr3, arr4)))
print(repr(np.matmul(arr4, arr3)))
# This will result in a ValueError:
# print(repr(np.matmul(arr3, arr3)))


27
array([[  5,   4,  -7],
       [  9,   8, -13],
       [ 13,  12, -19]])
array([[  4,   4],
       [-11, -10]])



# Time to Code!

We'll create a couple of matrix arrays to perform our math operations on. The first array will represent the matrix:

[[-0.5, 0.8, -0.1],

[0.0, -1.2, 1.3]]

The second array will represent the matrix:

[[1.2, 3.1],

[1.2, 0.3],

[1.5, 2.2]]

Set arr equal to np.array applied to a list of lists representing the first matrix.

Then set arr2 equal to np.array applied to a list of lists representing the second matrix.


In [21]:
import numpy as np

arr = np.array([[-0.5, 0.8, -0.1], [0.0, -1.2, 1.3]])

arr2 = np.array([[1.2, 3.1], [1.2, 0.3], [1.5, 2.2]])

print(repr(arr))
print("")
print(repr(arr2))

array([[-0.5,  0.8, -0.1],
       [ 0. , -1.2,  1.3]])

array([[1.2, 3.1],
       [1.2, 0.3],
       [1.5, 2.2]])


Next we'll apply some arithmetic to arr. Specifically, we'll do multiplication, addition, and squaring.

Set multiplied equal to arr multiplied by np.pi.

Then set added equal to the result of adding arr and multiplied.

Finally, set squared equal to added with each of its elements squared.
Python 3.5

In [22]:
multiplied = arr * np.pi
print(repr(multiplied))
print("")

added = arr + multiplied
print(repr(added))
print("")

squared = np.power(added, 2)
print(repr(squared))


array([[-1.57079633,  2.51327412, -0.31415927],
       [ 0.        , -3.76991118,  4.08407045]])

array([[-2.07079633,  3.31327412, -0.41415927],
       [ 0.        , -4.96991118,  5.38407045]])

array([[ 4.28819743, 10.97778541,  0.1715279 ],
       [ 0.        , 24.70001718, 28.98821461]])


After the arithmetic operations, we'll apply the base e exponential and logarithm to our array matrices.

Set exponential equal to np.exp applied to squared.

Then set logged equal to np.log applied to arr2.

In [23]:
exponential = np.exp(squared)
print(repr(exponential))
print("")

logged = np.log(arr2)
print(repr(logged))


array([[7.28350596e+01, 5.85587272e+04, 1.18711726e+00],
       [1.00000000e+00, 5.33434578e+10, 3.88527393e+12]])

array([[ 0.18232156,  1.13140211],
       [ 0.18232156, -1.2039728 ],
       [ 0.40546511,  0.78845736]])


Note that exponential has shape (2, 3) and logged has shape (3, 2). So we can perform matrix multiplication both ways.

Set matmul1 equal to np.matmul with first argument logged and second argument exponential. Note that matmul1 will have shape (3, 3).

Then set matmul2 equal to np.matmul with first argument exponential and second argument logged. Note that matmul2 will have shape (2, 2).

In [24]:
matmul1 = np.matmul(logged, exponential)
print(repr(matmul1))
print("")

matmul2 = np.matmul(exponential, logged)
print(repr(matmul2))


array([[ 1.44108036e+01,  6.03529115e+10,  4.39580713e+12],
       [ 1.20754286e+01, -6.42240618e+10, -4.67776415e+12],
       [ 3.03205327e+01,  4.20590657e+10,  3.06337283e+12]])

array([[ 1.06902790e+04, -7.04197733e+04],
       [ 1.58506868e+12,  2.99914875e+12]])
