# Notes

## NumPy Arrays

- When the elements of a NumPy array are mixed types, then the array's type will be upcast to the highest level type. This means that if an array input has mixed int and float elements, all the integers will be cast to their floating-point equivalents. If an array is mixed with int, float, and string elements, everything is cast to strings.

- NumPy arrays are faster than Python lists because they store elements in contiguous memory and support vectorized operations, reducing overhead and speeding up numerical computations.

- Similar to Python lists, when we make a reference to a NumPy array it doesn't create a different array. Therefore, if we change a value using the reference variable, it changes the original array as well. We get around this by using an array's inherent copy function.

- When we don't want a NumPy array to contain a value at a particular index, we can use np.nan to act as a placeholder. A common usage for np.nan is as a filler value for incomplete data.

The code below shows an example usage of np.nan. Note that np.nan cannot take on an integer type.

In [1]:
import numpy as np

arr = np.array([np.nan, 1, 2])
print(repr(arr))

array([nan,  1.,  2.])


## Using np.inf in NumPy
- To represent infinity in NumPy, we use the np.inf special value. We can also represent negative infinity with -np.inf.

- The code below shows an example usage of np.inf. **np.inf** cannot take on an integer type.

In [4]:
import numpy as np

print(np.inf > 1000000)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 5])
print(repr(arr))

True
array([inf,  5.])
array([-inf,   5.])


In [6]:
# Task 1: Set arr equal to np.array applied to the specified list.
arr = np.array([np.nan, 2, 3, 4, 5])
print(repr(arr))

array([nan,  2.,  3.,  4.,  5.])


In [10]:
# Task 2: Set arr2 equal to arr.copy(), then set the first element of arr2 equal to 10.
arr2 = arr.copy()
arr2[0] = 10
print(repr(arr2))

array([10.,  2.,  3.,  4.,  5.])


In [11]:
# Set float_arr equal to np.array applied to a list with elements 1, 5.4, and 3, in that order.

# Set float_arr2 equal to arr2.astype, with argument np.float32.

float_arr = np.array([1, 5.4, 3])
float_arr2 = arr2.astype(dtype=np.float32)
print(repr(float_arr))
print(repr(float_arr2))

array([1. , 5.4, 3. ])
array([10.,  2.,  3.,  4.,  5.], dtype=float32)


In [12]:
# Set matrix equal to np.array with a list of lists (representing the specified 2-D matrix) as the first argument, and np.float32 as the dtype keyword argument.

matrix = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)

print(repr(matrix))

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)
