# Random
## A. Random integers

Similar to the Python random module, NumPy has its own submodule for pseudo-random number generation called np.random. It provides all the necessary randomized operations and extends it to multi-dimensional arrays. To generate pseudo-random integers, we use the np.random.randint function.

The code below shows example usages of np.random.randint.

In [1]:
import numpy as np

print(np.random.randint(5))
print(np.random.randint(5))
print(np.random.randint(5, high=6))

random_arr = np.random.randint(-3, high=14,
                               size=(2, 2))
print(repr(random_arr))

2
1
5
array([[ 5, 13],
       [ 3,  4]], dtype=int32)


The np.random.randint function takes in a single required argument, which actually depends on the high keyword argument. If high=None (which is the default value), then the required argument represents the upper (exclusive) end of the range, with the lower end being 0. Specifically, if the required argument is n, then the random integer is chosen uniformly from the range [0, n).

If high is not None, then the required argument will represent the lower (inclusive) end of the range, while high represents the upper (exclusive) end.

The size keyword argument specifies the size of the output array, where each integer in the array is randomly drawn from the specified range. As a default, np.random.randint returns a single integer.

## B. Utility functions

Some fundamental utility functions from the np.random module are np.random.seed and np.random.shuffle. We use the np.random.seed function to set the random seed, which allows us to control the outputs of the pseudo-random functions. The function takes in a single integer as an argument, representing the random seed.

The code below uses np.random.seed with the same random seed. Note how the outputs of the random functions in each subsequent run are identical when we set the same random seed.


In [2]:
np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100, size=(2, 2))
print(repr(random_arr))

# New seed
np.random.seed(2)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100, size=(2, 2))
print(repr(random_arr))

# Original seed
np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100, size=(2, 2))
print(repr(random_arr))


5
array([[15, 75],
       [12, 78]], dtype=int32)
8
array([[18, 75],
       [25, 46]], dtype=int32)
5
array([[15, 75],
       [12, 78]], dtype=int32)


The np.random.shuffle function allows us to randomly shuffle an array. Note that the shuffling happens in place (i.e. no return value), and shuffling multi-dimensional arrays only shuffles the first dimension.

The code below shows example usages of np.random.shuffle. Note that only the rows of matrix are shuffled (i.e. shuffling along first dimension only).

In [3]:
vec = np.array([1, 2, 3, 4, 5])
np.random.shuffle(vec)
print(repr(vec))
np.random.shuffle(vec)
print(repr(vec))

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.random.shuffle(matrix)
print(repr(matrix))


array([3, 4, 2, 5, 1])
array([5, 3, 4, 2, 1])
array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])


## C. Distributions

Using np.random we can also draw samples from probability distributions. For example, we can use np.random.uniform to draw pseudo-random real numbers from a uniform distribution.

The code below shows usages of np.random.uniform.

In [4]:
print(np.random.uniform())
print(np.random.uniform(low=-1.5, high=2.2))
print(repr(np.random.uniform(size=3)))
print(repr(np.random.uniform(low=-3.4, high=5.9, size=(2, 2))))


0.3132735169322751
0.4408281904196243
array([0.44345289, 0.22957721, 0.53441391])
array([[5.09984683, 0.85200471],
       [0.60549667, 5.33388844]])


The function np.random.uniform actually has no required arguments. The keyword arguments, low and high, represent the inclusive lower end and exclusive upper end from which to draw random samples. Since they have default values of 0.0 and 1.0, respectively, the default outputs of np.random.uniform come from the range [0.0, 1.0).

The size keyword argument is the same as the one for np.random.randint, i.e. it represents the output size of the array.

Another popular distribution we can sample from is the normal (Gaussian) distribution. The function we use is np.random.normal.

The code below shows usages of np.random.normal.

In [5]:
print(np.random.normal())
print(np.random.normal(loc=1.5, scale=3.5))
print(repr(np.random.normal(loc=-2.4, scale=4.0, size=(2, 2))))


0.7252740646272712
4.772112039383628
array([[ 2.07318791, -2.17754724],
       [-0.89337346, -0.89545991]])


Like np.random.uniform, np.random.normal has no required arguments. The loc and scale keyword arguments represent the mean and standard deviation, respectively, of the normal distribution we sample from.

NumPy provides quite a few more built-in distributions, which are listed here.

## D. Custom sampling

While NumPy provides built-in distributions to sample from, we can also sample from a custom distribution with the np.random.choice function.

The code below shows example usages of np.random.choice.

In [6]:
colors = ["red", "blue", "green"]
print(np.random.choice(colors))
print(repr(np.random.choice(colors, size=2)))
print(repr(np.random.choice(colors, size=(2, 2), p=[0.8, 0.19, 0.01])))


green
array(['blue', 'red'], dtype='<U5')
array([['red', 'red'],
       ['blue', 'red']], dtype='<U5')


The required argument for np.random.choice is the custom distribution we sample from. The p keyword argument denotes the probabilities given to each element in the input distribution. Note that the list of probabilities for p must sum to 1.

In the example, we set p such that 'red' has a probability of 0.8 of being chosen, 'blue' has a probability of 0.19, and 'green' has a probability of 0.01. When p is not set, the probabilities are equal for each element in the distribution (and sum to 1).

# Time to Code!

We'll start off by obtaining some random integers. The first integer we get will be randomly chosen from the range [0, 5). The remaining integers will be part of a 3x5 NumPy array, each randomly chosen from the range [3, 10).

In [7]:
random1 = np.random.randint(5)
print(random1)
print("")

random_arr = np.random.randint(low = 3, high = 10, size = (3, 5))
print(random_arr)

4

[[3 4 6 7 5]
 [7 3 8 6 4]
 [5 3 7 4 5]]


The next two arrays will be drawn randomly from distributions. The first will contain 5 numbers drawn uniformly from the range [-2.5, 1.5].

In [9]:
random_uniform = np.random.uniform(low = -2.5, high = 1.5, size = 5)
print(random_uniform)

[-2.08709597 -0.7084259   1.13438201 -1.32554341 -1.34889865]


The second array will contain 50 numbers drawn from a normal distribution with mean 2.0 and standard deviation 3.5.

In [11]:
random_norm = np.random.normal(loc = 2.0, scale = 3.5, size = (10, 5))
print(random_norm)

[[ 2.70783669  3.59233285  0.6025614   2.63373596  4.82620783]
 [ 4.84387316  2.73815711  3.47622704  4.03673814  0.56427369]
 [10.03903136  7.90973969  4.19034015 -3.63977334  2.21034208]
 [ 3.61847276  4.39692772 -0.08411116  5.49667934  0.92140241]
 [ 3.2804342   7.62627466  1.16637921  0.80710101  3.70657972]
 [ 8.0867556   2.24139432  3.65634487 -0.27624258 -0.72687434]
 [-0.72181948  4.17896979  3.49646726  2.2590336   0.41390989]
 [ 4.11453774 10.34822035  1.56640835  0.86532214  3.08763981]
 [10.61569909  0.89356709 -4.35271969  4.39487325  2.11211385]
 [ 2.68694573  5.17607906 -5.47192186  4.85896512  6.14459958]]


We'll now create our own distribution of strings and randomly select from it. The values for our distribution will be 'a', 'b', 'c', 'd'.

To choose a value, we'll use a probability distribution of [0.5, 0.1, 0.2, 0.2], i.e. 'a' will have probability 0.5 of being chosen, 'b' will have a probability of 0.1, etc.

In [13]:
choices = ['a', 'b', 'c', 'd']
choice = np.random.choice(choices, p = [0.5, 0.1, 0.2, 0.2])
print(choice)

a


The last random operation we perform will be an in-place shuffle of a NumPy array.

In [16]:
arr = np.arange(start = 1, stop = 6)
print(arr)
print("")

np.random.shuffle(arr)
print(arr)

[1 2 3 4 5]

[2 4 3 5 1]
