# Statistics

## A. Analysis
It is often useful to analyze data for its main characteristics and interesting trends. There are few techniques in NumPy that allow us to quickly inspect data arrays.

For example, we can obtain minimum and maximum values of a NumPy array using its inherent min and max functions. This gives us an initial sense of the data's range, and can alert us to extreme outliers in the data.

The code below shows example usages of the min and max functions.

In [1]:
import numpy as np

arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(arr.min())
print(arr.max())

print(repr(arr.min(axis=0)))
print(repr(arr.max(axis=-1)))

-60
72
array([ -3,  -2, -60])
array([72,  3,  4])


The axis keyword argument is identical to how it was used in np.argmin and np.argmax from the chapter on Indexing. In our example, we use axis=0 to find an array of the minimum values in each column of arr and axis=1 to find an array of the maximum values in each row of arr.

## B. Statistical metrics

NumPy also provides basic statistical functions such as np.mean, np.var, and np.median, to calculate the mean, variance, and median of the data, respectively.

The code below shows how to obtain basic statistics with NumPy. Note that np.median applied without axis takes the median of the flattened array.

In [2]:
arr = np.array([[0, 72, 3], [1, 3, -60], [-3, -2, 4]])
print(np.mean(arr))
print(np.var(arr))
print(np.median(arr))
print(repr(np.median(arr, axis=-1)))


2.0
977.3333333333334
1.0
array([ 3.,  1., -2.])


# Time to Code!

Each coding exercise in this chapter will be to complete a small function that takes in a 2-D NumPy matrix (data) as input. The first function to complete is get_min_max, which returns the overall minimum and maximum element in data.

In [3]:
def get_min_max(data: np.array) -> tuple:
    overall_min = data.min()
    overall_max = data.max()
    return (overall_min, overall_max)


Next, we'll complete col_min, which returns the minimums across each column of data.

In [4]:
def col_min(data: np.array) -> np.array:
    min0 = data.min(axis=0)
    return min0


The final function to complete is basic_stats, which returns the mean, median, and variance of data.

In [5]:
def basic_stats(data: np.array) -> tuple:
    mean = np.mean(data)
    median = np.median(data)
    var = np.var(data)
    return (mean, median, var)
